### PR TITLE
Move to promises and add `.stop` and `.deregister`

### PR DESCRIPTION
**Pull request by jcgertig**

### CODE REVIEW

**Comment by jcgertig** [comment]
@Akamaozu I think this is as much as I can do in this pr.

**Comment by Akamaozu** [comment]
@jcgertig  No worries. You've already done a lot of awesome work; I'll take it from here.

I'll make a branch adding `supervisor.stop` and `supervisor.unregister`, then after merging those in, I'll create a pomisified version of the api.

Thanks for nudging me down the right direction.

**Comment by jcgertig** [comment]
What do expect the time frame to be. I needed this soon if possible.

**Comment by jcgertig** [comment]
@Akamaozu ^

**Comment by Akamaozu** [comment]
I've depromisified stop and deregister. 

Was writing tests to enforce expected behaviour and noticed using supervisor's `citizen.ref.kill()` doesn't set off supe's shutdown (or crash) lifecycle events. Not sure why yet.

I'm able to stop the process by sending a signal to it and getting it to stop itself. This seems sufficient but let me know if a different approach makes more sense.

I'll be done in the next few days if there are no more surprises :laughing:

**Comment by Akamaozu** [comment]
@jcgertig done with stop and deregister, to be specifc.

No timeline for promise api yet.

**Comment by jcgertig** [comment]
It should not require that the dev needs to handle the stop unless you are
adding some hidden mail that you auto handle. It does not trigger because
the code from a sigkill is null

**Comment by Akamaozu** [comment]
Don't worry. It'll be built into the citizen's supervision module.

It seems like there are circumstances where a process can exit and supe won't catch it.

Need to fix that.

**Pull request merged**
